#!/bin/bash
# Claude Code 세션 추출 스크립트

echo "🔍 Claude Code 세션 추출 가이드"
echo "================================"
echo ""
echo "📂 발견된 세션 파일:"
ls -lhS ~/.claude/projects/-home-user-n8n-copilot/*.jsonl
echo ""
echo "사용 가능한 명령어:"
echo ""
echo "1️⃣  claude-start"
echo "   → 대화형 UI로 세션 탐색 (추천)"
echo ""
echo "2️⃣  claude-search '검색어'"
echo "   → 특정 키워드 검색"
echo ""
echo "3️⃣  claude-extract"
echo "   → 모든 세션을 텍스트로 추출"
echo ""
echo "4️⃣  claude-logs"
echo "   → 로그 확인"
echo ""
echo "================================"
echo ""
echo "💡 추천 사용법:"
echo ""
echo "# 대화형 UI 실행 (가장 쉬움)"
echo "claude-start"
echo ""
echo "# 특정 키워드 검색"
echo "claude-search '무한로딩'"
echo "claude-search '계획'"
echo ""
echo "# 모든 대화를 파일로 저장"
echo "claude-extract > ~/all_sessions.txt"
echo ""
